# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'Finance' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Finance
  pod 'AFNetworking', '~> 3.1.0'
  pod 'YYModel', '~> 1.0.4'
  pod 'AESCrypt-ObjC', '~> 1.0.2'
  pod 'Masonry', '~> 1.0.2'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'PDTSimpleCalendar', '~> 0.9.1'
  pod 'ChameleonFramework'
  target 'FinanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinanceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
