# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'Finance' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Finance
  pod 'AFNetworking', '~> 3.1.0'
  pod 'YYModel', '~> 1.0.4'
  pod 'AESCrypt-ObjC', '~> 1.0.2'
  pod 'Masonry', '~> 1.0.2'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'PDTSimpleCalendar', '~> 0.9.1'
  pod 'ChameleonFramework'
  pod 'UMengAnalytics'
  pod 'WechatOpenSDK'
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'
  pod 'UIImage+SVG', '~> 0.1'
  pod 'PocketSVG'
  pod 'ReactiveObjC'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'DZNEmptyDataSet', '~> 1.8.1'
  pod 'iRate', '~> 1.12.1'
  pod 'MGSwipeTableCell', '~> 1.5.6'
  pod 'ios-charts', '~> 0.0.1'
  pod 'RETableViewManager', '~> 1.6'
  pod 'MDHTMLLabel', '~> 1.0.2'
  pod 'IQKeyboardManager'
  target 'FinanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinanceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
